# Generated by Django 3.1.2 on 2020-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_manager', '0001_auto_20201013_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_email_sent',
            field=models.BooleanField(default=False, verbose_name='Сообщение отправлено'),
        ),
    ]
