# Generated by Django 3.1.2 on 2020-10-14 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passes_manager', '0002_clients_is_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='is_email_sent',
            field=models.BooleanField(default=False, editable=False, verbose_name='Сообщение отправлено'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='is_registered',
            field=models.BooleanField(default=False, editable=False, verbose_name='Зарегистрирован'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
