# Generated by Django 3.1.2 on 2020-10-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_manager', '0004_auto_20201014_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий админа'),
        ),
    ]
