# Generated by Django 3.1.2 on 2020-10-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes_manager', '0005_applications_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='comment',
            new_name='comment_admin',
        ),
    ]
