# Generated by Django 3.1.2 on 2020-10-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_manager', '0006_auto_20201014_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='comment_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_get_year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи годового'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_push_onetime',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи на разовый'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_push_year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи на годовой'),
        ),
    ]
