# Generated by Django 3.1.2 on 2020-10-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_manager', '0007_auto_20201014_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-pk'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='car_number',
            field=models.CharField(max_length=11, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Пропуск выдан'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='zone',
            field=models.CharField(choices=[('m', 'МКАД'), ('t', 'ТТК'), ('s', 'СК')], max_length=1, verbose_name='Зона'),
        ),
    ]
