# Generated by Django 3.1.2 on 2020-10-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes_manager', '0010_auto_20201021_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='notify_client',
            field=models.BooleanField(default=False, verbose_name='Уведомить клиента'),
        ),
    ]
